name: Run Movieland Scraper

on:
  workflow_dispatch:     # Manual trigger
  schedule:
    - cron: '0 5 * * *'   # Runs daily at 5:00 AM UTC (8:30 AM Tehran time)

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py
    - name: Configure Git
      run: |
        git config user.name "AliBot"
        git config user.email "ali@example.com"

    - name: Commit .strm files
      run: |
        git add *.strm
        git commit -m "Update .strm files from scraper" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
